const express = require('express');
const http = require('http');
const path = require('path');
const { Server } = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = new Server(server);

app.use(express.static(path.join(__dirname, 'public')));

// Backup games — casual side activities outside the tournament's scoring
// system entirely (no leaderboard, no admin open/close gating). Each lives
// on its own Socket.IO namespace so it can't collide with the main game
// protocol above.
require('./uno-server.js')(io);
require('./ek-server.js')(io);
require('./go-server.js')(io);
require('./nien-server.js')(io);
require('./oaq-server.js')(io);
require('./battleship-server.js')(io);
require('./racing-server.js')(io);
require('./poker-server.js')(io);
require('./xq-server.js')(io);
require('./chess-server.js')(io);

const GAMES = ['sudoku', 'scramble', 'memory', 'proverb'];
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'trungthu2026!@';
const JOIN_WINDOW_MS = 5 * 60 * 1000;

// Lifetime attempt cap per game. Games not listed here are unlimited.
const MAX_ATTEMPTS = { sudoku: 3 };

// -- Tournament mode (all 4 games) ------------------------------------------
// Every scored game's Tournament mode shares the same lobby/pacing shell:
// players tournament:join a 'lobby' (see tournamentRound/tournamentParticipants
// below), the admin releases everyone together (admin:tournament-start), and
// each player's live in-progress score feeds tournamentLiveScores so the
// admin's Live Top Score page can show it. TOURNAMENT_GAMES (all 4) controls
// that shell; TOURNAMENT_CONTENT_SHARED_GAMES (Proverb/Scramble only)
// controls a second, separate thing -- actual shared puzzle CONTENT.
//
// For Proverb/Scramble, Tournament also hands everyone the exact same
// shuffled draw (see generateTournamentContent) and paces them through it
// question-by-question (questionIndex, admin:tournament-next) -- solo mode's
// own random draw isn't really comparable across players otherwise. Memory
// Match and Sudoku are deliberately left OUT of content-sharing: each player
// still gets their own random board/puzzle (same as Solo), so one player
// solving it can't hand the layout/answers to others in the same round.
// Picking Tournament there only gets you the shared lobby/live-score shell,
// plus tagging the attempt for the leaderboard -- totalQuestions is just 1
// (see freshTournamentRound), a single continuous attempt with no staged
// "next question" to advance through.
const TOURNAMENT_GAMES = GAMES;
const TOURNAMENT_CONTENT_SHARED_GAMES = ['proverb', 'scramble'];
const TOURNAMENT_PROVERB_POOL_SIZE = 40; // must match proverb.js's PROVERB_POOL.length
const TOURNAMENT_PROVERB_ROUNDS = 15; // must match proverb.js's ROUNDS_PER_GAME
const TOURNAMENT_SCRAMBLE_POOL_SIZE = 20; // must match scramble.js's WORD_POOL.length
const TOURNAMENT_SCRAMBLE_ROUND_LENGTH = 15; // Tournament-only round length (Solo stays scramble.js's WORDS_PER_GAME = 12)
// Fixed-position words for Tournament mode -- 1-based question number -> index
// into scramble.js's WORD_POOL. Must stay in sync with that array's order:
// index 12 is 'SMARTDEV', index 13 is 'CÔNG ĐOÀN'. Every Tournament round
// gets these two words at exactly these positions; the remaining positions
// are randomly drawn (without repeats) from the rest of the pool.
const TOURNAMENT_SCRAMBLE_FIXED_POSITIONS = { 10: 12, 15: 13 };

function shuffleArray(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// One shared content set per tournament-capable game -- regenerated by the
// admin (a "New Tournament Round" action) or generated lazily the first
// time anyone asks for it. Players already mid-game keep whatever content
// they already fetched; only players who join AFTER a regeneration get the
// new one, which is fine since this isn't a live synchronized round.
function generateTournamentContent(game) {
  if (game === 'proverb') {
    const indices = Array.from({ length: TOURNAMENT_PROVERB_POOL_SIZE }, (_, i) => i);
    return { proverbOrder: shuffleArray(indices).slice(0, TOURNAMENT_PROVERB_ROUNDS) };
  }
  if (game === 'scramble') {
    const fixedPositions = TOURNAMENT_SCRAMBLE_FIXED_POSITIONS; // { 10: 12, 15: 13 }
    const fixedIndices = new Set(Object.values(fixedPositions));
    const remainingPoolIndices = Array.from({ length: TOURNAMENT_SCRAMBLE_POOL_SIZE }, (_, i) => i)
      .filter((i) => !fixedIndices.has(i));
    const randomSlotCount = TOURNAMENT_SCRAMBLE_ROUND_LENGTH - fixedIndices.size;
    const randomDraw = shuffleArray(remainingPoolIndices).slice(0, randomSlotCount);

    const wordOrder = new Array(TOURNAMENT_SCRAMBLE_ROUND_LENGTH).fill(null);
    Object.entries(fixedPositions).forEach(([position, poolIndex]) => {
      wordOrder[Number(position) - 1] = poolIndex;
    });
    let randomCursor = 0;
    for (let i = 0; i < wordOrder.length; i += 1) {
      if (wordOrder[i] === null) wordOrder[i] = randomDraw[randomCursor++];
    }
    return { wordOrder };
  }
  return null;
}

const tournamentContent = {}; // game -> content, only for TOURNAMENT_GAMES
function getOrCreateTournamentContent(game) {
  if (!tournamentContent[game]) tournamentContent[game] = generateTournamentContent(game);
  return tournamentContent[game];
}

// game -> Map<playerId, { name, score, updatedAt }> -- each player's LIVE,
// in-progress score for their current Tournament attempt at that game.
// Distinct from players.scores[game] (only updated once a run fully
// finishes, see score:submit): this updates after every single question/word
// a player answers, so everyone currently in that Tournament can watch the
// lead change in real time. Reset per-player on a fresh tournament:join
// (so a new attempt doesn't start out "leading" on a stale old score), and
// entirely whenever the admin starts a new tournament round.
const tournamentLiveScores = {};
TOURNAMENT_GAMES.forEach((g) => { tournamentLiveScores[g] = new Map(); });

// game -> Map<playerId, name> -- every distinct player who has joined the
// CURRENT tournament round for that game (added on tournament:join, kept
// even after they finish so the "X joined" count stays accurate for the
// whole round). Reset only when the admin starts a new tournament round.
const tournamentParticipants = {};
TOURNAMENT_GAMES.forEach((g) => { tournamentParticipants[g] = new Map(); });

// Sudoku and Memory Match generate a fresh random puzzle/board per attempt
// (unlike Scramble/Proverb's identical shared content for everyone), so a
// retry there is fair and meaningful -- each joined participant gets up to
// TOURNAMENT_MAX_ATTEMPTS plays within the current round (see
// tournament:request-attempt below), independent of Sudoku's separate
// lifetime Solo+Tournament cap (MAX_ATTEMPTS). Reset whenever the admin
// starts a new tournament round.
const TOURNAMENT_RETRY_GAMES = ['sudoku', 'memory'];
const TOURNAMENT_MAX_ATTEMPTS = 3;
const tournamentAttempts = {}; // game -> Map<playerId, attemptsUsed>
TOURNAMENT_RETRY_GAMES.forEach((g) => { tournamentAttempts[g] = new Map(); });

// Best-first live standings, capped at `limit` -- used for both the
// tournament:top-score broadcast (always sends up to 10, so clients can
// expand from 3 to 10 without a round-trip) and the initial tournament:join
// snapshot.
// Each entry tracks TWO numbers, not one -- see tournament:question-done:
//  - bestFinalScore: only ever raised by a CONFIRMED completed attempt
//    (Scramble/Proverb's every report; Sudoku/Memory's finish/give-up/timeout).
//  - liveScore: the current honest in-progress value for whichever attempt
//    is active right now (Sudoku/Memory only -- their score can rise AND
//    fall within one attempt, e.g. a decaying speed bonus, so this is NOT
//    maxed against its own past ticks the way bestFinalScore is).
// The displayed/ranked score is always max(bestFinalScore, liveScore), so an
// in-progress peek never permanently overrides -- or gets confused with -- a
// worse but already-confirmed result from giving up or timing out.
function liveStandings(game, limit = 10) {
  return [...tournamentLiveScores[game].values()]
    .map((e) => ({ name: e.name, score: Math.max(e.bestFinalScore, e.liveScore) }))
    .sort((a, b) => b.score - a.score || a.name.localeCompare(b.name))
    .slice(0, limit);
}

function tournamentSnapshot(game) {
  return { playerCount: tournamentParticipants[game].size, top: liveStandings(game, 10) };
}

function broadcastTournamentTop(game) {
  io.emit('tournament:top-score', { game, ...tournamentSnapshot(game) });
}

// One-shot initial snapshot for a freshly-connecting socket -- without this,
// a client that opens (or refreshes) the Live Top Score page after the last
// tournament:question-done for a round would see nothing at all, since
// tournament:top-score only fires on a NEW score change, not on connect.
function allTournamentSnapshots() {
  const result = {};
  TOURNAMENT_GAMES.forEach((g) => { result[g] = tournamentSnapshot(g); });
  return result;
}

// game -> { phase: 'lobby' | 'active', questionIndex, totalQuestions } -- the
// server-authoritative pacing for a synchronized Tournament round. Players
// who tournament:join land in the 'lobby' (and are the only ones who CAN
// join -- see tournament:join below) until admin:tournament-start moves
// everyone to questionIndex 0 together. Each question still runs on its own
// client-side ROUND_SECONDS clock (see each game's roundTick), but nothing
// advances to the NEXT question until admin:tournament-next bumps
// questionIndex and broadcasts it -- there's no client-side auto-advance in
// Tournament mode any more. Reset to a fresh lobby whenever the admin starts
// a new tournament round.
function freshTournamentRound(game) {
  // Sudoku/Memory have no staged "questions" to advance through -- a single
  // continuous attempt, so totalQuestions is just 1 (admin:tournament-next
  // is never valid/needed for them, same as after Proverb/Scramble's last
  // question).
  let totalQuestions = 1;
  if (game === 'scramble') totalQuestions = TOURNAMENT_SCRAMBLE_ROUND_LENGTH;
  else if (game === 'proverb') totalQuestions = TOURNAMENT_PROVERB_ROUNDS;
  return { phase: 'lobby', questionIndex: -1, totalQuestions };
}
const tournamentRound = {};
TOURNAMENT_GAMES.forEach((g) => { tournamentRound[g] = freshTournamentRound(g); });

function roundStatePayload(game) {
  const round = tournamentRound[game];
  const players = [...tournamentParticipants[game].values()].sort((a, b) => a.localeCompare(b));
  return {
    game,
    phase: round.phase,
    questionIndex: round.questionIndex,
    totalQuestions: round.totalQuestions,
    playerCount: players.length,
    players,
  };
}

function broadcastRoundState(game) {
  io.emit('tournament:round-state', roundStatePayload(game));
}

function allRoundStates() {
  const result = {};
  TOURNAMENT_GAMES.forEach((g) => { result[g] = roundStatePayload(g); });
  return result;
}

// game -> Set<playerId> -- who has finished (correctly answered, timed out,
// or otherwise resolved) the CURRENT questionIndex, see tournament:question-done
// below. Once this covers every joined participant, the turn ends early for
// anyone still watching their own clock (e.g. Scramble's "answered correctly,
// waiting out the rest of the 60s") instead of making them wait it out for no
// reason. Reset whenever the round advances (start/next) or resets.
const tournamentQuestionDone = {};
TOURNAMENT_GAMES.forEach((g) => { tournamentQuestionDone[g] = new Set(); });

// playerId -> { name, scores: { sudoku, scramble, memory, proverb }, attempts: { ... }, updatedAt }
const players = new Map();

// Recent anti-cheat flags (tab-switch disqualifications, brute-force/impossible-speed
// suspicions), newest last. Visible only to the admin panel, not the public leaderboard.
const cheatFlags = [];
const MAX_CHEAT_FLAGS = 200;
let nextFlagId = 1;
const adminSocketIds = new Set();

function recordCheatFlag({ playerId, name, game, reason, detail }) {
  const flag = {
    id: nextFlagId++,
    playerId,
    name: sanitizeName(name),
    game: GAMES.includes(game) ? game : 'unknown',
    reason: String(reason || 'unknown').slice(0, 60),
    detail: String(detail || '').slice(0, 200),
    at: Date.now(),
  };
  cheatFlags.push(flag);
  if (cheatFlags.length > MAX_CHEAT_FLAGS) cheatFlags.shift();
  adminSocketIds.forEach((id) => io.to(id).emit('admin:cheat-flag', flag));
  return flag;
}

// Per-game gate controlling whether players may start that specific game.
// Each game is closed by default; admin opens one at a time, and it
// auto-closes again after JOIN_WINDOW_MS — independently of the others.
const gameWindows = {};
const closeTimers = {};
GAMES.forEach((g) => {
  gameWindows[g] = { openedAt: null, closesAt: null };
});

// Separate from the join-gating window above: fully hides a game from the
// index page's grid (replaced with a card-back "Open later" placeholder)
// regardless of whether its join window is open/closed. Admin-only, ON by
// default for all 4 games — the admin reveals each one when it's time.
const gameHidden = {};
GAMES.forEach((g) => { gameHidden[g] = true; });

// Separate again from both of the above: hides just the Tournament option
// within an otherwise-visible/open game -- players can still play Solo, they
// just won't see a Tournament button on that game's mode-select screen. Off
// by default (Tournament available for all 4 games) until the admin turns
// it off for one.
const tournamentHidden = {};
GAMES.forEach((g) => { tournamentHidden[g] = false; });

function gameWindowSnapshot(game) {
  const w = gameWindows[game];
  const isOpen = w.closesAt !== null && Date.now() < w.closesAt;
  return {
    game,
    isOpen,
    openedAt: w.openedAt,
    closesAt: w.closesAt,
    hidden: Boolean(gameHidden[game]),
    tournamentHidden: Boolean(tournamentHidden[game]),
  };
}

function allGameWindowsSnapshot() {
  const result = {};
  GAMES.forEach((g) => {
    result[g] = gameWindowSnapshot(g);
  });
  return result;
}

function broadcastGameWindow(game) {
  io.emit('game-window', gameWindowSnapshot(game));
}

function openGameWindow(game) {
  const now = Date.now();
  gameWindows[game] = { openedAt: now, closesAt: now + JOIN_WINDOW_MS };
  clearTimeout(closeTimers[game]);
  closeTimers[game] = setTimeout(() => broadcastGameWindow(game), JOIN_WINDOW_MS);
  broadcastGameWindow(game);
}

function closeGameWindowNow(game) {
  clearTimeout(closeTimers[game]);
  gameWindows[game] = { ...gameWindows[game], closesAt: Date.now() };
  broadcastGameWindow(game);
}

function clampScore(n, max = 1500) {
  const num = Number(n);
  if (!Number.isFinite(num)) return 0;
  return Math.max(0, Math.min(max, Math.round(num)));
}

// Both Scramble and Proverb's Tournament mode can hit 100 points per
// word/round (Scramble always could; Proverb's Tournament-only decaying
// formula now can too, vs. Solo's 40-point-max checkpoints), and each has 15
// of them, so 15 * 100 = 1500 base alone -- the cap is raised to 1800 there
// to leave room for the same up-to-300 speed bonus. Every other game/mode
// keeps the default 1500 cap.
function maxScoreFor(game, mode) {
  if (mode === 'tournament' && (game === 'scramble' || game === 'proverb')) return 1800;
  return 1500;
}

function sanitizeName(name) {
  const clean = String(name || 'Player').trim().slice(0, 20);
  return clean || 'Player';
}

function sanitizeDetail(detail) {
  return String(detail || '').trim().slice(0, 80);
}

function totalFor(player) {
  return GAMES.reduce((sum, g) => sum + (player.scores[g] || 0), 0);
}

function leaderboardSnapshot() {
  return [...players.entries()]
    .map(([id, p]) => ({
      id,
      name: p.name,
      scores: p.scores,
      details: p.details,
      total: totalFor(p),
      updatedAt: p.updatedAt,
      gameUpdatedAt: p.gameUpdatedAt,
    }))
    .sort((a, b) => b.total - a.total || a.name.localeCompare(b.name));
}

// Top N players for one game's score alone, in rank order — used only for
// the admin-triggered reveal ceremony snapshot (see admin:reveal-results).
function topForGame(gameKey, limit) {
  return [...players.values()]
    .filter((p) => (p.scores[gameKey] || 0) > 0)
    .map((p) => ({ name: p.name, total: p.scores[gameKey], detail: p.details[gameKey] || '' }))
    .sort((a, b) => b.total - a.total || a.name.localeCompare(b.name))
    .slice(0, limit);
}

function getOrCreatePlayer(playerId) {
  let player = players.get(playerId);
  if (!player) {
    player = {
      name: 'Player',
      scores: { sudoku: 0, scramble: 0, memory: 0, proverb: 0 },
      details: { sudoku: '', scramble: '', memory: '', proverb: '' },
      attempts: { sudoku: 0, scramble: 0, memory: 0, proverb: 0 },
      gameUpdatedAt: { sudoku: 0, scramble: 0, memory: 0, proverb: 0 },
      updatedAt: 0,
    };
    players.set(playerId, player);
  }
  return player;
}

// Fake players for previewing the leaderboard UI — never runs automatically
// against real event data (see admin:seed-demo-data / SEED_DEMO_DATA below).
// IDs are prefixed "demo_" so they're easy to find and remove as a group.
const DEMO_PLAYERS = [
  { name: 'Lan Nguyễn', scores: { sudoku: 1500, scramble: 1120, memory: 1400, proverb: 1350 },
    details: { sudoku: '48s · 0 mistakes', scramble: '140s · 12 of 12 words solved', memory: '300s · 150 moves', proverb: '500s · 15 of 15 proverbs solved' } },
  { name: 'Hoa Đỗ', scores: { sudoku: 1490, scramble: 1080, memory: 1350, proverb: 1300 },
    details: { sudoku: '55s · 0 mistakes', scramble: '145s · 12 of 12 words solved', memory: '350s · 160 moves', proverb: '510s · 15 of 15 proverbs solved' } },
  { name: 'Minh Trần', scores: { sudoku: 1420, scramble: 980, memory: 1250, proverb: 1180 },
    details: { sudoku: '52s · 1 mistake', scramble: '150s · 10 of 12 words solved', memory: '410s · 210 moves', proverb: '620s · 13 of 15 proverbs solved' } },
  { name: 'Linh Cao', scores: { sudoku: 1400, scramble: 1000, memory: 1300, proverb: 1150 },
    details: { sudoku: '70s · 1 mistake', scramble: '155s · 11 of 12 words solved', memory: '380s · 180 moves', proverb: '550s · 13 of 15 proverbs solved' } },
  { name: 'Trang Lê', scores: { sudoku: 1350, scramble: 1040, memory: 1150, proverb: 1000 },
    details: { sudoku: '90s · 2 mistakes', scramble: '160s · 11 of 12 words solved', memory: '500s · 240 moves', proverb: '680s · 12 of 15 proverbs solved' } },
  { name: 'Đức Vũ', scores: { sudoku: 1180, scramble: 0, memory: 1480, proverb: 1220 },
    details: { sudoku: '140s · 3 mistakes', scramble: '', memory: '190s · 70 moves', proverb: '560s · 14 of 15 proverbs solved' } },
  { name: 'Thảo Vương', scores: { sudoku: 1250, scramble: 950, memory: 1100, proverb: 1080 },
    details: { sudoku: '120s · 2 mistakes', scramble: '165s · 10 of 12 words solved', memory: '520s · 260 moves', proverb: '600s · 13 of 15 proverbs solved' } },
  { name: 'Tuấn Bùi', scores: { sudoku: 1050, scramble: 1000, memory: 1020, proverb: 0 },
    details: { sudoku: '180s · 4 mistakes', scramble: '170s · 10 of 12 words solved', memory: '600s · 280 moves', proverb: '' } },
  { name: 'Mai Đặng', scores: { sudoku: 0, scramble: 890, memory: 0, proverb: 960 },
    details: { sudoku: '', scramble: '180s · 9 of 12 words solved', memory: '', proverb: "Time's up · 11 of 15 proverbs solved" } },
  { name: 'Hùng Phạm', scores: { sudoku: 980, scramble: 760, memory: 900, proverb: 850 },
    details: { sudoku: '210s · 5 mistakes', scramble: '200s · 8 of 12 words solved', memory: '700s · 320 moves', proverb: '750s · 10 of 15 proverbs solved' } },
  { name: 'Nam Hoàng', scores: { sudoku: 800, scramble: 700, memory: 850, proverb: 780 },
    details: { sudoku: '250s · 6 mistakes', scramble: '210s · 7 of 12 words solved', memory: "Time's up · 51/64 pairs matched · 350 moves", proverb: '800s · 9 of 15 proverbs solved' } },
  { name: 'Khánh Đinh', scores: { sudoku: 600, scramble: 500, memory: 600, proverb: 550 },
    details: { sudoku: '300s · 8 mistakes', scramble: '220s · 6 of 12 words solved', memory: "Time's up · 40/64 pairs matched · 400 moves", proverb: '850s · 7 of 15 proverbs solved' } },
];

function seedDemoData() {
  const now = Date.now();
  DEMO_PLAYERS.forEach((demo, i) => {
    players.set(`demo_${i + 1}`, {
      name: demo.name,
      scores: { sudoku: 0, scramble: 0, memory: 0, proverb: 0, ...demo.scores },
      details: { sudoku: '', scramble: '', memory: '', proverb: '', ...demo.details },
      attempts: { sudoku: 0, scramble: 0, memory: 0, proverb: 0 },
      gameUpdatedAt: { sudoku: now, scramble: now, memory: now, proverb: now },
      updatedAt: now,
    });
  });
  return DEMO_PLAYERS.length;
}

function clearDemoData() {
  let removed = 0;
  [...players.keys()].forEach((id) => {
    if (id.startsWith('demo_')) {
      players.delete(id);
      removed += 1;
    }
  });
  return removed;
}

// Removes any player record created by a load-test/bot-simulation script --
// every such script this session has prefixed its synthetic playerIds with
// "bot-" or "test-" (never used by a real client), so this can clean up
// simulated data without touching real players.
function clearBotData() {
  let removed = 0;
  [...players.keys()].forEach((id) => {
    if (id.startsWith('bot-') || id.startsWith('test-')) {
      players.delete(id);
      removed += 1;
    }
  });
  return removed;
}

io.on('connection', (socket) => {
  socket.emit('leaderboard', leaderboardSnapshot());
  socket.emit('game-window-all', allGameWindowsSnapshot());
  socket.emit('tournament:round-state-all', allRoundStates());
  socket.emit('tournament:top-score-all', allTournamentSnapshots());

  socket.on('admin:login', ({ password }, callback) => {
    const ok = typeof password === 'string' && password === ADMIN_PASSWORD;
    if (ok) {
      socket.isAdmin = true;
      adminSocketIds.add(socket.id);
    }
    if (typeof callback === 'function') {
      callback({
        ok,
        state: ok ? allGameWindowsSnapshot() : undefined,
        playerCount: ok ? players.size : undefined,
        flags: ok ? cheatFlags.slice(-50).reverse() : undefined,
        // Bundled directly into the response (rather than relying on the
        // connection-time broadcasts) since a listener for those only gets
        // attached AFTER login succeeds -- by then the one-shot connection
        // broadcast has already fired and would otherwise be missed,
        // leaving e.g. the Live Top Score page showing nothing until the
        // next live score change.
        roundStates: ok ? allRoundStates() : undefined,
        topScores: ok ? allTournamentSnapshots() : undefined,
      });
    }
  });

  socket.on('admin:open', ({ game }, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    if (!GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid game' });
      return;
    }
    openGameWindow(game);
    if (typeof callback === 'function') callback({ ok: true, state: gameWindowSnapshot(game) });
  });

  socket.on('admin:close', ({ game }, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    if (!GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid game' });
      return;
    }
    closeGameWindowNow(game);
    if (typeof callback === 'function') callback({ ok: true, state: gameWindowSnapshot(game) });
  });

  socket.on('admin:set-hidden', ({ game, hidden }, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    if (!GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid game' });
      return;
    }
    gameHidden[game] = Boolean(hidden);
    broadcastGameWindow(game);
    if (typeof callback === 'function') callback({ ok: true, state: gameWindowSnapshot(game) });
  });

  socket.on('admin:set-tournament-hidden', ({ game, hidden }, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    if (!GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid game' });
      return;
    }
    tournamentHidden[game] = Boolean(hidden);
    broadcastGameWindow(game);
    if (typeof callback === 'function') callback({ ok: true, state: gameWindowSnapshot(game) });
  });

  socket.on('register', ({ playerId, name }) => {
    if (typeof playerId !== 'string' || !playerId) return;
    const player = getOrCreatePlayer(playerId);
    player.name = sanitizeName(name);
    io.emit('leaderboard', leaderboardSnapshot());
  });

  socket.on('score:submit', ({ playerId, name, game, score, detail, mode }) => {
    if (typeof playerId !== 'string' || !playerId) return;
    if (!GAMES.includes(game)) return;

    const player = getOrCreatePlayer(playerId);
    if (name) player.name = sanitizeName(name);
    const incoming = clampScore(score, maxScoreFor(game, mode));
    // Only replace the stored detail (time/moves/etc.) when this run matches
    // or beats the recorded best, so it always describes THAT score, not
    // whatever run happened to submit most recently.
    if (incoming >= (player.scores[game] || 0)) {
      player.details[game] = sanitizeDetail(detail);
    }
    player.scores[game] = Math.max(player.scores[game] || 0, incoming);
    const now = Date.now();
    player.updatedAt = now;
    player.gameUpdatedAt[game] = now;

    io.emit('leaderboard', leaderboardSnapshot());
  });

  // Reserves one of the player's lifetime attempts for a game before they're
  // allowed to see the board. Consumed on request, not on completion, so a
  // disqualified (tab-switch) run still costs an attempt like a normal one.
  socket.on('game:start-attempt', ({ playerId, name, game }, callback) => {
    if (typeof playerId !== 'string' || !playerId || !GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid request' });
      return;
    }
    const player = getOrCreatePlayer(playerId);
    if (name) player.name = sanitizeName(name);
    const max = MAX_ATTEMPTS[game] || null;
    const used = player.attempts[game] || 0;
    if (max && used >= max) {
      if (typeof callback === 'function') callback({ ok: false, error: 'max-attempts', attemptsUsed: used, attemptsMax: max });
      return;
    }
    player.attempts[game] = used + 1;
    if (typeof callback === 'function') callback({ ok: true, attemptsUsed: player.attempts[game], attemptsMax: max });
  });

  // Reserves one of a player's TOURNAMENT_MAX_ATTEMPTS retries within the
  // CURRENT tournament round (Sudoku/Memory only -- see TOURNAMENT_RETRY_GAMES).
  // Separate from game:start-attempt's lifetime Solo+Tournament cap above:
  // this only gates retries inside an already-active Tournament round, and
  // resets on admin:new-tournament-round, not per-player ever.
  socket.on('tournament:request-attempt', ({ playerId, game }, callback) => {
    if (typeof playerId !== 'string' || !playerId || !TOURNAMENT_RETRY_GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid-game' });
      return;
    }
    if (tournamentRound[game].phase !== 'active') {
      if (typeof callback === 'function') callback({ ok: false, error: 'not-active' });
      return;
    }
    const used = tournamentAttempts[game].get(playerId) || 0;
    if (used >= TOURNAMENT_MAX_ATTEMPTS) {
      if (typeof callback === 'function') {
        callback({ ok: false, error: 'exhausted', attemptsUsed: used, attemptsMax: TOURNAMENT_MAX_ATTEMPTS });
      }
      return;
    }
    tournamentAttempts[game].set(playerId, used + 1);
    if (typeof callback === 'function') {
      callback({ ok: true, attemptsUsed: used + 1, attemptsMax: TOURNAMENT_MAX_ATTEMPTS });
    }
  });

  // Anti-cheat signal from a game page (tab-switch disqualification, brute-force
  // guess pattern, implausible solve speed, ...). Never blocks play server-side —
  // it's surfaced to the admin panel for a human to judge.
  socket.on('cheat:flag', ({ playerId, name, game, reason, detail }) => {
    if (typeof playerId !== 'string' || !playerId) return;
    recordCheatFlag({ playerId, name, game, reason, detail });
  });

  // Clears everyone's used-attempt count for one game (or all games), without
  // touching scores — for undoing lockouts during testing or between rounds.
  socket.on('admin:reset-attempts', ({ game }, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    if (game && !GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid game' });
      return;
    }
    const gamesToReset = game ? [game] : GAMES;
    let playerCount = 0;
    players.forEach((player) => {
      gamesToReset.forEach((g) => { player.attempts[g] = 0; });
      playerCount += 1;
    });
    if (typeof callback === 'function') callback({ ok: true, playerCount, games: gamesToReset });
  });

  // Hands out the current shared shuffle/draw for a tournament-capable game
  // and places the player in its Tournament lobby, generating fresh content
  // on first request if this is the very first player to ask. Only reachable
  // while the round is still in the 'lobby' phase -- once the admin has
  // started it (admin:tournament-start), late joiners are turned away and
  // have to wait for the admin to start a new round (admin:new-tournament-round
  // resets back to 'lobby'). Anyone can call this (no admin gate) --
  // Tournament mode is still only reachable from a page already behind that
  // game's normal join-window gate, same as Solo mode.
  socket.on('tournament:join', ({ playerId, name, game }, callback) => {
    if (!TOURNAMENT_GAMES.includes(game)) { if (typeof callback === 'function') callback({ ok: false, error: 'invalid-game' }); return; }
    if (tournamentRound[game].phase !== 'lobby') {
      if (typeof callback === 'function') callback({ ok: false, error: 'round-in-progress' });
      return;
    }
    const content = getOrCreateTournamentContent(game);
    if (typeof playerId === 'string' && playerId) {
      tournamentParticipants[game].set(playerId, sanitizeName(name));
      // A fresh attempt starts out with no live score of its own -- otherwise
      // this player would keep "leading" on their last attempt's final tally
      // until they answer their first question in the new one.
      tournamentLiveScores[game].delete(playerId);
      broadcastTournamentTop(game); // playerCount (and maybe the standings) just changed
      broadcastRoundState(game); // playerCount just changed too
    }
    if (typeof callback === 'function') {
      callback({ ok: true, content, standings: tournamentSnapshot(game), round: roundStatePayload(game) });
    }
  });

  // A tournament player reports that they've finished (correctly answered,
  // timed out, or otherwise resolved) the CURRENT question/word -- not just
  // to update their live score (like the old tournament:progress this
  // replaces), but so the server can tell once EVERY joined participant has
  // finished this question and end the turn early for anyone still waiting
  // out their own clock (see tournament:question-over below). A stale report
  // -- the round having since moved on, or the wrong questionIndex -- is
  // ignored, since it can't mean anything for the CURRENT question.
  // `final` marks this report as a CONFIRMED completed attempt (Scramble/
  // Proverb: every report, since each is a question actually resolving;
  // Sudoku/Memory: only finish/give-up/timeout, not the periodic in-progress
  // ticks from updateLiveScore()) -- see liveStandings() above for why that
  // distinction matters.
  socket.on('tournament:question-done', ({ playerId, name, game, questionIndex, score, final }) => {
    if (typeof playerId !== 'string' || !playerId) return;
    if (!TOURNAMENT_GAMES.includes(game)) return;
    const round = tournamentRound[game];
    if (round.phase !== 'active' || questionIndex !== round.questionIndex) return;
    const incoming = clampScore(score, maxScoreFor(game, 'tournament'));
    const existing = tournamentLiveScores[game].get(playerId) || { bestFinalScore: 0, liveScore: 0 };
    tournamentLiveScores[game].set(playerId, {
      name: sanitizeName(name),
      bestFinalScore: final ? Math.max(existing.bestFinalScore, incoming) : existing.bestFinalScore,
      // Reset the transient once an attempt concludes -- a fresh retry's own
      // ticks will repopulate it, so it never carries over a now-irrelevant
      // in-progress value from the attempt that just ended.
      liveScore: final ? 0 : incoming,
      updatedAt: Date.now(),
    });
    broadcastTournamentTop(game);
    if (final) {
      tournamentQuestionDone[game].add(playerId);
      if (tournamentQuestionDone[game].size >= tournamentParticipants[game].size) {
        io.emit('tournament:question-over', { game, questionIndex });
      }
    }
  });

  // Regenerates a fresh shared shuffle/draw for a tournament-capable game and
  // resets its round back to a fresh 'lobby' -- e.g. to start a brand new
  // round once the current one has finished (or to abort one in progress).
  // Players already mid-question keep playing with their old content to a
  // natural finish (their local `words`/`rounds` array was already fetched at
  // join time), but the shared pacing (admin:tournament-start/-next) is reset,
  // so anyone still waiting on a "next question" from the old round is now
  // stuck -- only expected to be used between rounds, not mid-round.
  socket.on('admin:new-tournament-round', ({ game }, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    if (!TOURNAMENT_GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid-game' });
      return;
    }
    tournamentContent[game] = generateTournamentContent(game);
    tournamentLiveScores[game] = new Map();
    tournamentParticipants[game] = new Map();
    tournamentQuestionDone[game] = new Set();
    tournamentRound[game] = freshTournamentRound(game);
    if (TOURNAMENT_RETRY_GAMES.includes(game)) tournamentAttempts[game] = new Map();
    broadcastTournamentTop(game);
    broadcastRoundState(game);
    if (typeof callback === 'function') callback({ ok: true });
  });

  // Releases everyone currently in a Tournament's lobby to start question 0
  // together. Only valid from the 'lobby' phase (see tournament:join, which
  // stops accepting new joins once this fires).
  socket.on('admin:tournament-start', ({ game }, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    if (!TOURNAMENT_GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid-game' });
      return;
    }
    if (tournamentRound[game].phase !== 'lobby') {
      if (typeof callback === 'function') callback({ ok: false, error: 'already-started' });
      return;
    }
    tournamentRound[game].phase = 'active';
    tournamentRound[game].questionIndex = 0;
    tournamentQuestionDone[game] = new Set();
    broadcastRoundState(game);
    if (typeof callback === 'function') callback({ ok: true });
  });

  // Releases everyone currently waiting (their own question having already
  // ended) into the next question. Not valid once the last question has
  // already begun -- there's nothing further to advance to; each player's own
  // client finishes their run locally when their final question ends.
  socket.on('admin:tournament-next', ({ game }, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    if (!TOURNAMENT_GAMES.includes(game)) {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid-game' });
      return;
    }
    const round = tournamentRound[game];
    if (round.phase !== 'active') {
      if (typeof callback === 'function') callback({ ok: false, error: 'not-active' });
      return;
    }
    if (round.questionIndex + 1 >= round.totalQuestions) {
      if (typeof callback === 'function') callback({ ok: false, error: 'already-last-question' });
      return;
    }
    round.questionIndex += 1;
    tournamentQuestionDone[game] = new Set();
    broadcastRoundState(game);
    if (typeof callback === 'function') callback({ ok: true });
  });

  // Populates (or clears) the fake players above for previewing the leaderboard
  // UI. Admin-only, and never runs on its own — see SEED_DEMO_DATA below for
  // the opt-in startup version.
  socket.on('admin:seed-demo-data', (payload, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    const count = seedDemoData();
    io.emit('leaderboard', leaderboardSnapshot());
    if (typeof callback === 'function') callback({ ok: true, count });
  });

  socket.on('admin:clear-demo-data', (payload, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    const removed = clearDemoData();
    io.emit('leaderboard', leaderboardSnapshot());
    if (typeof callback === 'function') callback({ ok: true, removed });
  });

  socket.on('admin:clear-bot-data', (payload, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    const removed = clearBotData();
    io.emit('leaderboard', leaderboardSnapshot());
    if (typeof callback === 'function') callback({ ok: true, removed });
  });

  // Snapshots the current top 10 for ONE board ('overall' or a game key) in
  // rank order and broadcasts it so the big-screen leaderboard can run that
  // board's reveal ceremony. The client freezes on this snapshot for the
  // animation — it does not reflect scores that come in mid-ceremony. Each
  // of the 5 boards is revealed independently, on its own admin button.
  socket.on('admin:reveal-results', ({ board }, callback) => {
    if (!socket.isAdmin) {
      if (typeof callback === 'function') callback({ ok: false, error: 'not authorized' });
      return;
    }
    let top10;
    if (board === 'overall') {
      top10 = leaderboardSnapshot().filter((p) => p.total > 0).slice(0, 10);
    } else if (GAMES.includes(board)) {
      top10 = topForGame(board, 10);
    } else {
      if (typeof callback === 'function') callback({ ok: false, error: 'invalid board' });
      return;
    }
    io.emit('reveal-results', { board, top10 });
    if (typeof callback === 'function') callback({ ok: true, count: top10.length });
  });

  socket.on('disconnect', () => {
    adminSocketIds.delete(socket.id);
  });
});

// Opt-in only (never fires by default) — set SEED_DEMO_DATA=1 to preview the
// leaderboard with fake players without needing to log into the admin panel.
if (process.env.SEED_DEMO_DATA) {
  const count = seedDemoData();
  console.log(`Seeded ${count} demo players onto the leaderboard (SEED_DEMO_DATA is set).`);
}

const PORT = process.env.PORT || 3001;
server.listen(PORT, '0.0.0.0', () => {
  console.log(`Autumn Festival Tournament running on port ${PORT}`);
  console.log('On this machine:  http://localhost:' + PORT);
  console.log('For everyone on the same wifi, find this PC\'s LAN IP (ipconfig)');
  console.log('and share:        http://<this-pc-ip>:' + PORT);
  console.log('Big-screen leaderboard: http://<this-pc-ip>:' + PORT + '/leaderboard.html');
  console.log('Admin panel:            http://<this-pc-ip>:' + PORT + '/admin.html');
  console.log('Live top score (admin): http://<this-pc-ip>:' + PORT + '/tournament-live.html');
  if (!process.env.ADMIN_PASSWORD) {
    console.log(`Admin password (default, set ADMIN_PASSWORD env var to change): ${ADMIN_PASSWORD}`);
  }
});
